version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/db/chat.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
    volumes:
      - ./db:/app/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/personas"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 可选：添加本地LLM服务（如需要）
  # local-llm:
  #   image: local-llm-image
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - MODEL_PATH=/models
  #   volumes:
  #     - ./models:/models
  #   restart: unless-stopped